# isuue のための label を定義します

## Base
- name: bug
  color: D73A4A
  description: 重大なバグ
- name: chore
  color: FEF2C0
  description: 雑多な修正や更新
- name: docs
  color: 0075CA
  description: ドキュメントの追加や修正、更新
- name: enhance
  color: 00FBFF
  description: 特に重要な実装
- name: icebox
  color: C5DEF5
  description: wip、いつか解決したいが今は手を出せない
- name: question
  color: 5319E7
  description: 疑問や問題提起
- name: UI/UX
  color: BFDADC
  description: 見た目やユーザー体験の向上
- name: wont
  color: FFFFFF
  description: 必須ではない、エキストラな修正

## OS
- name: os:Windows
  color: 4B4B4B
  description: MS Windows 関連
- name: os:macOS
  color: 4B4B4B
  description: macOS 関連
- name: os:Linux
  color: 4B4B4B
  description: Linux Distro 関連
- name: os:Android
  color: 4B4B4B
  description: Android 関連
- name: os:iOS/iPadOS
  color: 4B4B4B
  description: iOS/iPadOS 関連

## Device
- name: device:SP
  color: D6D6D6
  description: Mobile 端末関連
- name: device:PC
  color: D6D6D6
  description: PC 関連

## Browser
- name: browser:Chrome
  color: D4C5F9
  description: Google Chrome 関連
- name: browser:Firefox
  color: D4C5F9
  description: Firefox 関連
- name: browser:Safari
  color: D4C5F9
  description: Safari 関連
- name: browser:Edge
  color: D4C5F9
  description: Edge 関連
